server:
  port: 8080

spring:
  application:
    name: gateway-application
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    config:
      enabled: true
      uri: http://localhost:9296
  main:
    web-application-type: reactive

eureka:
  instance:
    prefer-ip-address: true

jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP



