server:
  port: 9001

spring:
  application:
    name: auth-service
  cloud:
    config:
      enabled: true
      uri: http://localhost:9296

eureka:
  instance:
    prefer-ip-address: true

jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
  expiration: 86400
