server:
  port: 9297

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HelenBarskaya/config-server.git
          clone-on-start: true
      enabled: true
      uri: https://localhost:9296

eureka:
  instance:
    prefer-ip-address: true